import { orderRankField } from "@sanity/orderable-document-list";
import { defineArrayMember, defineField, defineType } from "sanity";
import { ACTIVITY_TYPES, activityLabels, DIFFICULTIES } from "@/lib/trips";
import { isTranslation, languageField, titleWithLanguage } from "./language";

export const trip = defineType({
  name: "trip",
  title: "Trip",
  type: "document",
  groups: [
    { name: "basics", title: "Basics", default: true },
    { name: "photos", title: "Photos" },
    { name: "itinerary", title: "Itinerary" },
    { name: "included", title: "Included" },
  ],
  fields: [
    languageField("basics"),
    defineField({ name: "title", type: "string", group: "basics", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Web address",
      type: "slug",
      group: "basics",
      readOnly: isTranslation,
      description: "The last part of the trip's URL, in every language. Click Generate after typing the title. Changing it breaks old links.",
      options: { source: "title", maxLength: 80 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "activityType",
      title: "Category",
      type: "string",
      group: "basics",
      readOnly: isTranslation,
      options: { list: ACTIVITY_TYPES.map((value) => ({ value, title: activityLabels[value] })), layout: "radio" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      rows: 5,
      group: "basics",
      description: "Overview paragraph. The first ~150 characters are also used for Google and trip cards.",
      validation: (r) => r.required(),
    }),
    defineField({ name: "duration", type: "string", group: "basics", description: 'e.g. "5 days"', validation: (r) => r.required() }),
    defineField({
      name: "difficulty",
      type: "string",
      group: "basics",
      readOnly: isTranslation,
      description: "Translated automatically on French and Hebrew pages.",
      options: { list: [...DIFFICULTIES], layout: "radio", direction: "horizontal" },
      validation: (r) => r.required(),
    }),
    defineField({ name: "groupSize", type: "string", group: "basics", description: 'A maximum like "10 people", or a range like "3–5 people".', validation: (r) => r.required() }),
    defineField({ name: "bestSeason", type: "string", group: "basics", description: 'e.g. "Jun – Sep"', validation: (r) => r.required() }),
    defineField({ name: "start", title: "Starts at", type: "string", group: "basics", validation: (r) => r.required() }),
    defineField({ name: "end", title: "Ends at", type: "string", group: "basics", description: "Same as the start for a round trip.", validation: (r) => r.required() }),
    defineField({ name: "stay", title: "Accommodation", type: "string", group: "basics", description: 'e.g. "Homestays & camping"', validation: (r) => r.required() }),
    defineField({
      name: "heroImage",
      title: "Main photo",
      type: "imageWithAlt",
      group: "photos",
      description: "Shown at the top of the trip page and on trip cards. Use a wide landscape photo.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "gallery",
      type: "array",
      group: "photos",
      description: "Drag to reorder. The first five appear in the mosaic; the rest open in the viewer. Leave empty to show just the main photo.",
      of: [defineArrayMember({ type: "photo" })],
      options: { layout: "grid" },
    }),
    defineField({
      name: "itinerary",
      title: "Day-by-day itinerary",
      type: "array",
      group: "itinerary",
      of: [defineArrayMember({ type: "dayPlan" })],
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "elevationProfile",
      title: "Elevation chart",
      type: "array",
      group: "itinerary",
      description: "Optional. Trail points in order from the trailhead. The chart appears when there are at least two points.",
      of: [defineArrayMember({ type: "waypoint" })],
    }),
    defineField({ name: "inclusions", title: "What's included", type: "array", group: "included", of: [defineArrayMember({ type: "string" })] }),
    defineField({ name: "exclusions", title: "Not included", type: "array", group: "included", of: [defineArrayMember({ type: "string" })] }),
    orderRankField({ type: "trip", hidden: true }),
  ],
  orderings: [{ title: "Website order", name: "orderRank", by: [{ field: "orderRank", direction: "asc" }] }],
  preview: {
    select: { title: "title", duration: "duration", type: "activityType", media: "heroImage", language: "language" },
    prepare: ({ title, duration, type, media, language }) => ({
      title,
      subtitle: titleWithLanguage([activityLabels[type as keyof typeof activityLabels], duration].filter(Boolean).join(" · "), language),
      media,
    }),
  },
});
